name: funny_kanji
description: A new Flutter project.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  hive: ^2.0.5
  yaru: ^0.2.2
  yaru_icons: ^0.1.2
  kplayer: ^0.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data